language: haskell

env:
  matrix:
    - HPVER=2013.2.0.0 CABALVER=1.18
    - HPVER=2014.2.0.0 CABALVER=1.18
    - GHCVER=7.4.2 CABALVER=1.18
    - GHCVER=7.6.3 CABALVER=1.18
    - GHCVER=7.8.4 CABALVER=1.18
    - GHCVER=7.10.1 CABALVER=1.22
    - GHCVER=head CABALVER=head
  global:
    - HEAD_DEPS="diagrams-core diagrams-solve active dual-tree"

matrix:
  allow_failures:
    - env: GHCVER=7.4.2 CABALVER=1.18
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh


notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-lib\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
